name: Fetch
on: workflow_dispatch

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Test Internet
        run: |
          curl -I https://www.google.com
          curl -I https://www.wikipedia.org
          curl https://ipinfo.io
          
      - name: Download file (optional)
        run: |
          # اگر فایلی می‌خوای دانلود کنی، آدرسش را اینجا بگذار:
          # curl -L https://example.com/file.zip -o myfile.zip
          echo "Ready to download"
          
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: result
          path: .
